GHA var tweaking

diff --git a/.github/workflows/publish_release.yaml b/.github/workflows/publish_release.yaml
--- a/.github/workflows/publish_release.yaml
+++ b/.github/workflows/publish_release.yaml
@@ -14,6 +14,14 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v4.1.1
 
+      - name: Check if tag follows SemVer
+        id: semver-check
+        run: |
+            if ! [[ "${{ github.event.ref }}" =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9]+)?$ ]]; then
+              echo "Invalid tag format. Tags must follow SemVer (e.g., v1.0.0)."
+              exit 1
+            fi
+
   create-release:
     runs-on: ubuntu-latest
     needs: check-tag
@@ -30,8 +38,8 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
-          tag_name: ${{ github.ref_name }}
-          release_name: Release ${{ github.ref_name }}
+          tag_name: ${{ github.event.ref }}
+          release_name: Release ${{ github.event.ref }}
           body: ${{ steps.release_notes.outputs.notes }}
           draft: false
           prerelease: false
